# Generated by Django 4.2 on 2024-11-25 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=100,
                unique=True,
                validators=[django.core.validators.EmailValidator],
            ),
        ),
    ]
